# Generated by Django 3.1.4 on 2020-12-22 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Milking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Manager.cow')),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Manager.cowtype'),
        ),
        migrations.AddField(
            model_name='cow',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Manager.cow'),
        ),
    ]
