# Generated by Django 3.1.4 on 2020-12-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='isMilking',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateTimeField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.cow')),
            ],
        ),
    ]
