# Generated by Django 3.1.4 on 2020-12-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20201225_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
