# Generated by Django 3.1.4 on 2021-01-04 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_auto_20210104_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmilking',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
