# Generated by Django 3.1.4 on 2021-01-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_auto_20210105_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowpregnancy',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cowpregnancy_child', to='Manager.cow'),
        ),
        migrations.AddField(
            model_name='cowpregnancy',
            name='success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cowpregnancy',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cowpregnancy_mother', to='Manager.cow'),
        ),
    ]
